### ISSUE TITLE
after run.bat get error

### ISSUE THREAD

**Issue by Tg00174** [sim0n00ps/L3-Dumping#4]
Traceback (most recent call last):
  File "C:\OD\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
  File "C:\OD\dumper-main\Helpers\Scanner.py", line 7, in <module>
    from Helpers.wv_proto2_pb2 import SignedLicenseRequest
  File "C:\OD\dumper-main\Helpers\wv_proto2_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\Users\Admin\AppData\Roaming\Python\Python310\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by sim0n00ps** [comment]
Run pip install protobuf==3.20.3
