### ISSUE TITLE
Last part set up issue

### ISSUE THREAD

**Issue by Wameeey** [sim0n00ps/L3-Dumping#6]
Traceback (most recent call last):
  File "C:\Users\wendela\Desktop\New folder (2)\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
  File "C:\Users\wendela\Desktop\New folder (2)\dumper-main\Helpers\Scanner.py", line 3, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
Press any key to continue . . .

tried the one in the issues but didnt work

**Comment by Wameeey** [comment]
i fixed it by ranaming the crypto folder into Crypto in Python

the problem now is its not generating any key_dumps

**Comment by Wameeey** [comment]
the bat generates this file in my dumper-main   "license_request.bin"
